services:
  app:
    build: .
    ports:
      - 8000:8000
    # working_dir: /api
    environment:
      MYSQL_HOST: music-db
      MYSQL_USER: root
      MYSQL_PASSWORD: zenor0
      MYSQL_DB: music_down_site
    networks:
      - backends
    depends_on:
      - music-db

# docker run -dp 8000:8000 --network test-be `
# -e MYSQL_HOST=music-db `
# -e MYSQL_USER=root `
# -e MYSQL_PASSWORD=zenor0 `
# -e MYSQL_DB=music_down_site `
# fastapi 


  music-db:
    image: mysql:8.0
    volumes:
      - music-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: zenor0
      MYSQL_DATABASE: music_down_site
    networks:
      - backends
    expose:
      - 3306

# docker run -d `
# --network test-be --network-alias music-db `
# -v music-mysql-data:/var/lib/mysql `
# -e MYSQL_ROOT_PASSWORD=zenor0 `
# -e MYSQL_DATABASE=music_down_site `
# mysql:8.0

networks:
  backends:

volumes:
  music-mysql-data: